#!/usr/bin/python
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import importlib

import imagelib.layout
import imagelib.layout.samus

parser = argparse.ArgumentParser(
    description='Build a firmware image from its components')

parser.add_argument('--layout', '-l', dest='layout', default=None,
		    help='Layout to use for this image')
parser.add_argument('-o', dest='output_file', default='image.bin',
		    help='Output image file name')

def main():
    (options, layout_args) = parser.parse_known_args()
    if not options.layout:
        raise RuntimeError('No layout specified')
    layout = options.layout

    if not layout in imagelib.layout.layouts:
        raise RuntimeError('Layout %s is unrecognized.' % layout)

    layout_module = importlib.import_module('.' + layout, 'imagelib.layout')

    image = layout_module.prepare(layout_args)

    with open(options.output_file, mode="wb", buffering=0) as output:
        output.write(image.build())

if __name__ == '__main__':
    main()
